name: ci cd client - dev
on:
  - workflow_dispatch
jobs:
  build:
    name: Run test and deploy
    runs-on:
      - self-hosted
      - new-dev
    steps:
      - name: Make envfile
        run: |
          echo "REACT_APP_API_URL=http://34.229.153.54/api" > .env
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
