name: ci cd client - dev
on:
  - workflow_dispatch
jobs:
  build:
    name: Run test and deploy
    runs-on:
      - self-hosted
      - runner-dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          clean: false
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
